services:

  example-frontend:
    image: example-frontend
    ports:
      - 5000:5000
    
  example-backend:
    image: example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - REQUEST_ORIGIN=http://localhost
    ports:
      - 8080:8080
    depends_on: 
      - db
      
  redis:
    image: redis
    
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
        
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
    depends_on:
      - example-frontend

volumes:
  database:
  
