services:

  example-frontend:
    image: example-frontend
    ports:
      - 5000:5000
    
  example-backend:
    image: example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
    ports:
      - 8080:8080
      
  redis:
    image: redis
    
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
